pub fn jobs() -> &'static [(fn(), &'static str)] {
    &[
        // (day1::main, "day1"),
        // (day2::main, "day2"),
        // (day3::main, "day3"),
        // (day4::main, "day4"),
        // (day5::main, "day5"),
        (day6::main, "day6"),
        (day7::main, "day7"),
        // (day7::main, "day7"),
        // (day8::main, "day8"),
        // (day8::main, "day8"),
        // (day9::main, "day9"),
        // (day9::main, "day9"),
        // (day10::main, "day10"),
        // (day10::main, "day10"),
        // (day11::main, "day11"),
        // (day11::main, "day11"),
        // (day12::main, "day12"),
        // (day12::main, "day12"),
        // (day13::main, "day13"),
        // (day13::main, "day13"),
        // (day14::main, "day14"),
        // (day14::main, "day14"),
        // (day15::main, "day15"),
        // (day15::main, "day15"),
        // (day16::main, "day16"),
        // (day16::main, "day16"),
        // (day17::main, "day17"),
        // (day17::main, "day17"),
        // (day18::main, "day18"),
        // (day18::main, "day18"),
        // (day19::main, "day19"),
        // (day19::main, "day19"),
        // (day20::main, "day20"),
        // (day20::main, "day20"),
        // (day21::main, "day21"),
        // (day21::main, "day21"),
        // (day22::main, "day22"),
        // (day22::main, "day22"),
        // (day23::main, "day23"),
        // (day23::main, "day23"),
        // (day24::main, "day24"),
        // (day24::main, "day24"),
        // (day25::main, "day25"),
    ]
}
